gravity_compensation_controller:
  ros__parameters:
    type: "pal_controllers/GravityCompensationController"
    dt: 0.01

    motor_torque_constants: ["arm_1_joint", "arm_2_joint", "arm_3_joint", "arm_4_joint", "arm_5_joint", "arm_6_joint", "arm_7_joint"]

    motor_torque_constants: ["COMMAND", "COMMAND", "COMMAND", "COMMAND", "COMMAND", "ZERO_TORQUE", "ZERO_TORQUE"]

    motor_torque_constants: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]

    reduction_ratios: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]

    static_frictions: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

    viscous_frictions: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

    velocity_tolerances: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]



